
package sd.tp1.clt.ws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "FileServerSOAPService", targetNamespace = "http://svr.tp1.sd/", wsdlLocation = "http://localhost:8080/FileServer?wsdl")
public class FileServerSOAPService
    extends Service
{

    private final static URL FILESERVERSOAPSERVICE_WSDL_LOCATION;
    private final static WebServiceException FILESERVERSOAPSERVICE_EXCEPTION;
    private final static QName FILESERVERSOAPSERVICE_QNAME = new QName("http://svr.tp1.sd/", "FileServerSOAPService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/FileServer?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        FILESERVERSOAPSERVICE_WSDL_LOCATION = url;
        FILESERVERSOAPSERVICE_EXCEPTION = e;
    }

    public FileServerSOAPService() {
        super(__getWsdlLocation(), FILESERVERSOAPSERVICE_QNAME);
    }

    public FileServerSOAPService(WebServiceFeature... features) {
        super(__getWsdlLocation(), FILESERVERSOAPSERVICE_QNAME, features);
    }

    public FileServerSOAPService(URL wsdlLocation) {
        super(wsdlLocation, FILESERVERSOAPSERVICE_QNAME);
    }

    public FileServerSOAPService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, FILESERVERSOAPSERVICE_QNAME, features);
    }

    public FileServerSOAPService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public FileServerSOAPService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns FileServerSOAP
     */
    @WebEndpoint(name = "FileServerSOAPPort")
    public FileServerSOAP getFileServerSOAPPort() {
        return super.getPort(new QName("http://svr.tp1.sd/", "FileServerSOAPPort"), FileServerSOAP.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns FileServerSOAP
     */
    @WebEndpoint(name = "FileServerSOAPPort")
    public FileServerSOAP getFileServerSOAPPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://svr.tp1.sd/", "FileServerSOAPPort"), FileServerSOAP.class, features);
    }

    private static URL __getWsdlLocation() {
        if (FILESERVERSOAPSERVICE_EXCEPTION!= null) {
            throw FILESERVERSOAPSERVICE_EXCEPTION;
        }
        return FILESERVERSOAPSERVICE_WSDL_LOCATION;
    }

}
